### ISSUE TITLE
Dependancy on oidc module

### ISSUE THREAD

**Issue by ademone** [GEANT/shib-idp-profile#1]
When trying to access the profile page on a plain install of 4.3, got the error 
``` 
Shibboleth/idp/flows/userprofile/userprofile-beans.xml]: Cannot resolve reference to bean 'shibboleth.oidc.RevocationCache' while setting bean property 'revocationCache'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.oidc.RevocationCache' available
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.oidc.RevocationCache' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:874)
```
Meaning you have to install the oidc module. But from version 4.2 you have to install also oidc common and oidc config modules.

**Comment by jalauros** [comment]
Latest pre-release that you can download now should have a fix for that.
